Iter5
arefev/mtrcstore pull request #1
Opened 2024-10-28 09:14 UTC by arefev

Реализован сервер и агент.
В Makefile вынесены скрипты для сборки и запуска приложений:
- make build - скомпилирует сервер и агент
- make server - запустит сервер
- make agent - запустит воркер агента

2024-10-29 13:09 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.
2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

2024-10-29 13:09 UTC, s-shpak commented on Makefile
> +server-build:
К таргетам Makefile'а следует добавлять аттрибут `.PHONY`: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

```suggestion
.PHONY: server-build
server-build:
```

2024-10-29 13:09 UTC, s-shpak commented on Makefile
> +server: server-build server-run
Лучше написать зависимость так:

```
server: server-run

server-run: server-build

server-build:
```

2024-10-29 13:09 UTC, s-shpak commented on cmd/agent/flags.go
Название выбрано неудачно: это не только флаги, но и переменные окружения

2024-10-29 13:09 UTC, s-shpak commented on cmd/agent/flags.go
> +		log.Fatal(err)
Фаталиться в глубине кода нельзя: прокидывай ошибку наверх и вызывай `log.Fatal` на самом верхнем уровне (в функции `main()`)

2024-10-29 13:09 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Паниковать не надо: используй `log.Fatal` для:
1. отображения ошибки
2. завершения процесса с ошибкой

2024-10-29 13:09 UTC, s-shpak commented on cmd/server/main.go
> +	config := ParseFlags()
Я бы посоветовал тебе `ParseFlags` также вызывать в `run`

2024-10-29 13:09 UTC, s-shpak commented on cmd/agent/main.go
> +func main() {
Лучше организовать код так же, как в точке входа сервера: с функциями `main()` и `run()`

2024-10-29 13:09 UTC, s-shpak commented on cmd/server/main_test.go
> +	storage := repository.NewMemory()
Проще создавать эти сущности заново для каждого тест-кейса: это недорого, и ты точно сможешь гарантировать, что запуск одного теста не повляиется на результаты другого, т.к. они будут работать всегда с новыми сущностями

2024-10-29 13:09 UTC, s-shpak commented on internal/server/repository/memory.go
> +		return float64(val), nil
Подумай, как можно обойтись без дополнительного каста в `float64`

2024-10-29 13:09 UTC, s-shpak commented on internal/server/middleware/checktype.go
> +func CheckType(next http.Handler) http.Handler {
Я не уверен, что валидацию входящих запросов нужно делать на уровне интерфейса взаимодействия с клиентом: это, скорее, бизнес-правило, потому эту проверку лучше поместить на слой бизнес-логики.

У тебя еще будет возможность написать middleware для сервиса

2024-10-29 13:09 UTC, s-shpak commented on internal/server/service/metricshtml.go
> +func MetricsHTML(list map[string]float64) string {
Это необязательно, но можешь попробовать использовать этот пакет для вывода html-контента: https://pkg.go.dev/html/template

2024-10-29 13:09 UTC, s-shpak commented on internal/server/service/metricshtml.go
> +		li += fmt.Sprintf("<li>%s: %f</li>", name, val)
Лучше распечатывать `counter` как целое число: так пользователю будет понятнее, о какой метрике идет речь. Если переделаешь хранилище так, что оно будет возвращать целые числа для счетчиков, то отлично. Если решишь делать без этого, то нужно правильно отформатировать число здесь

2024-10-29 13:09 UTC, s-shpak commented on internal/agent/repository/storage.go
> +type Storage interface {
В данном случае маловероятно, что тип хранилища, используемый на клиенте изменится. Потому будет правильно объявить интрефейс там, где он используется

2024-10-29 13:09 UTC, s-shpak commented on internal/agent/worker.go
> +func (w *Worker) getReportURL(mType string, name string, val float64) string {
1. Счетчики лучше отправлять как целые числа
2. Эта функция -- просто обертка над строковым шаблоном. Кажется, что проще поместить всю эту логику напрямую в те функции, где она вызывавется

2024-10-29 13:09 UTC, s-shpak commented on internal/agent/worker.go
> +			log.Fatal(err)
Нельзя фаталиться из глубины кода

2024-10-29 21:20 UTC, arefev commented
все замечания исправлены

2024-10-30 15:07 UTC, s-shpak requested changes
Забыл попросить: добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

2024-10-30 15:07 UTC, s-shpak commented on cmd/server/config.go
> +	f.Parse(os.Args[1:])
Я бы разделил логику, которая зависит от внешнего окружения (`os.Args`), и чистые функции для простоты тестирования. В этом случае у тебя будет отдельная функция, которая будет принимать на вход слайс строк, парсить его, и возвращать объект конфигурации

2024-10-30 15:07 UTC, s-shpak commented on cmd/server/config.go
> +		return Config{}, err
Ошибки изсторонних пакетов надо оборачивать при помощи `fmt.Errorf` и `%w`. Здесь смотри подробнее как: https://go.dev/blog/go1.13-errors#wrapping-errors-with-w

2024-10-30 15:07 UTC, s-shpak commented on internal/agent/worker.go
> +			log.Print(err)
При логировании ошибки добавляй к ней контекст:

```suggestion
			log.Printf("failed to send the metric %s: %w", gaugeName, err)
```

2024-10-30 15:07 UTC, s-shpak commented on internal/server/handler/metric.go
> +	// "fmt"
deadcode

2024-10-30 21:41 UTC, arefev commented
проработал замечания, подключил линтер и пофиксил ошибки

2024-10-31 00:54 UTC, s-shpak requested changes
Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-10-31 00:54 UTC, s-shpak commented on cmd/agent/main.go
> +	if err := config.InitFlags(os.Args[1:]); err != nil {
Кажется, что композировать объект конфигурации в `run` не нужно: лучше сделать это внутри `NewConfig`. После этого функции для разбора флагов и переменных окружения можно сделать неэкспортируемыми

2024-10-31 05:46 UTC, arefev commented on cmd/agent/main.go
> +	if err := config.InitFlags(os.Args[1:]); err != nil {
поправил )

2024-10-31 18:51 UTC, s-shpak approved these changes

2024-10-31 19:03 UTC, merged