Iter9
arefev/mtrcstore pull request #2
Opened 2024-11-15 13:05 UTC by arefev

2024-11-18 09:12 UTC, s-shpak requested changes

2024-11-18 09:12 UTC, s-shpak commented on internal/server/logger/logger.go
> +var Log *zap.Logger
Я не советую использовать глобальный логгер. Такая практика встречается, но я предлагаю не использовать ее в курсе.

Единственный аргумент для использования глобального логгера -- возможность не передавать его напрямую в компоненты, где он используется. При этом использование глобального логгера несет в себе все минусы глобальных переменных, а также минусы самого глобального логгера.

Можно выделить две основные проблемы "глобального" подхода: 

1. Теперь ты не можешь кастомизировать логгер для конкретного компонента, в котором он используется. Например, если логгер явным образом передается в компонент при его инициализации, то ты можешь настроить его так, чтобы к каждому сообщению добавлялось поле с именем компонента, который это сообщение сгенерировал. Вобщем, локальные логгеры кастомизируются легко, глобальные -- сложно.

2. С одной стороны, удобно, что логгер не надо явным образом передавать в компонент. С другой, теперь мы создаем неявные зависимости: поведение компонента зависит от логгера (если, например, логгер не будет корректно проинициализирован, то компонент тоже поломается, т.к. при вызове логгера будет падать). Неявные зависимости хуже чем явные. Потому с моей т.з. передавать логгер явным образом как аргумент функции, или как поле объекта -- лучше, чем спрятать его в глобальную переменную

2024-11-18 09:12 UTC, s-shpak commented on cmd/server/main.go
> +	log.Printf("Log level %s\n", config.LogLevel)
Если ты используешь кастомный логгер, то не используй `log` в коде. Его использование оправдано только если ты логируешь что-то до инициализации кастомного логгера.

2024-11-18 09:12 UTC, s-shpak commented on cmd/server/main_test.go
> +			fmt.Printf("%v", err)
После добавления логгера в проект `fmt.Print`/`fmt.Println`/`fmt.Printf` использовать нельзя.

2024-11-18 09:12 UTC, s-shpak commented on cmd/server/main_test.go
> +				fmt.Printf("logger init failed: %v", err)
Это тот самый случай, когда можно использовать `log`

2024-11-18 09:12 UTC, s-shpak commented on internal/agent/model/metric.go
> +func (m *Metric) ToJSON() (string, error) {
А зачем этот метод ? Стандартный JSON-энкодер делает то же самое

2024-11-18 09:12 UTC, s-shpak commented on internal/agent/service/report.go
> +	url := fmt.Sprintf("%s%s/%s", protocol, host, updateURLPath)
Здесь лучше использовать https://pkg.go.dev/net/url@go1.22.7#JoinPath чтобы не ошибиться с разделителями

2024-11-18 09:12 UTC, s-shpak commented on internal/agent/service/report.go
> +func (r *Report) compress(s string) (io.Writer, error) {
Возвращать лучше конкретный тип, а не интерфейс (вспомни про обсуждение на первом вебинаре)

2024-11-18 09:12 UTC, s-shpak commented on internal/server/handler/metric.go
> +	ival := int64(mValue)
В Go не принято обозначать тип перменной через суффикс.

```suggestion
	delta := int64(mValue)
```

2024-11-18 09:12 UTC, s-shpak commented on internal/server/handler/metric.go
> +	check := func(m model.Metric, mType string, err error) {
Немного грязно получилось: лучше вынеси это в отдельную функцию и возвращай из нее ошибку и, может быть, статус-код (хотя можно и только ошибку, а статус код получать через ее тип)

2024-11-18 09:12 UTC, s-shpak commented on internal/server/handler/metric.go
> +		logger.Log.Error("handler UpdateJson metrics: json decode failed", zap.Error(err))
Штатные ошибки (не 5**) не стоит логироваться: они будут только зашумлять логи

2024-11-18 09:12 UTC, s-shpak commented on internal/server/middleware/compress.go
> +			cw := service.NewCompressWriter(w)
```suggestion
			ow = service.NewCompressWriter(w)
```

2024-11-18 09:12 UTC, s-shpak commented on internal/server/middleware/compress.go
> +			// Почему-то не вызывается WriteHeader из ow
А в чем проблема ?

2024-11-18 09:12 UTC, s-shpak commented on internal/server/middleware/compress.go
> +				w.WriteHeader(http.StatusInternalServerError)
Здесь не хватает `return`

2024-11-19 10:10 UTC, arefev commented on internal/server/middleware/compress.go
> +			cw := service.NewCompressWriter(w)
так не получилось сделать, т.к. обязательно надо вызывать метод Close(), появлялась ошибка
![image](https://github.com/user-attachments/assets/14fcdac8-f11e-4c54-8358-88fa52b9448d)

2024-11-20 12:48 UTC, s-shpak requested changes

2024-11-20 12:48 UTC, s-shpak commented on cmd/server/main.go
> +	log.Printf("Log level %s\n", config.LogLevel)
Это пока не исправлено: пройдись по коду и посмотри, где ты используешь пакет `log`. После инициализации корневого логгера, использовать стоит только этот логгер

2024-11-20 12:48 UTC, s-shpak commented on cmd/server/main.go
> +	go worker.
С такой архитектурой могут быть проблемы: если данные вообще не будут храниться в памяти, а, например, только в БД, то аткивация такого воркера не будет иметь смысл. Я бы сделал этот воркер компонентом нового хранилища, чтобы он не вызывался напрямую из `main`, а работал как часть хранилища.

Здесь я описал это подробнее: https://app.pachca.com/chats/15060382?message=380573810

если ты не хочешь делать это в текущей итерации, то можем отложить до следующей, но, кажется, что в какой-то момент это придется менять

2024-11-21 12:55 UTC, s-shpak requested changes

2024-11-21 12:55 UTC, s-shpak commented on internal/server/repository/file.go
> +var workerRunnig = false
Глобальные переменные не нужны

2024-11-21 16:09 UTC, s-shpak approved these changes

2024-11-21 16:12 UTC, merged