Iter13
arefev/mtrcstore pull request #3
Opened 2024-11-27 10:51 UTC by arefev

2024-11-29 13:51 UTC, s-shpak requested changes

2024-11-29 13:51 UTC, s-shpak commented on cmd/server/main.go
> +func initStorage(config *Config, cLog *zap.Logger) (storage repository.Storage, storageType string, err error) {
А зачем здесь возвращать именованные значения ?

2024-11-29 13:51 UTC, s-shpak commented on docker-compose.yaml
> +    image: postgres
Версии образа лучше указывать. Особенно это справедливо для посгреса, который печально извесетн своими ломающими изменениями в новых версиях

2024-11-29 13:51 UTC, s-shpak commented on docker-compose.yaml
> +version: '3.9'
Попробуй обновить `docker compose` в последних версиях указывать версию не надо

2024-11-29 13:51 UTC, s-shpak commented on internal/agent/service/report.go
> +		log.Printf("massSend(): failed to send metrics, %s", err.Error())
Я бы рекомендовал прокинуть эту ошибку выше, пусть компонент который запустил отправку, сам принимает решение, как ее обработать

2024-11-29 13:51 UTC, s-shpak commented on internal/agent/service/report.go
>  		return fmt.Errorf("send failed: %w", err)
Сообщение должно быть другим

2024-11-29 13:51 UTC, s-shpak commented on internal/retry/retry.go
> +		if err == nil || !r.checkErr(err) || r.attempt == r.max {
Последнее уже проверяется выше

```suggestion
		if err == nil || !r.checkErr(err) {
```

Я понимаю, что ты добавил эту проверку, чтобы не вызывать `wait` лишний раз, но попробуй упростить код и обойтись здесь без дублирования логики

2024-11-29 13:51 UTC, s-shpak commented on internal/retry/retry.go
> +type Action func() error
А почему один тип, используемый в экспортируемом методе, экспортируется, а другой нет ?

2024-11-29 13:51 UTC, s-shpak commented on internal/retry/retry.go
> +	r.attempt++
Я бы разделил инкремент количества попыток и расчет времени паузы

2024-11-29 13:51 UTC, s-shpak commented on internal/server/repository/db.go
> +		ON CONFLICT (type, name)
Потенциально здесь может произойти коллизия по разным причинам, попробуй более гранулировано определить, что проблема именно из-за того, что метрика с таким именем уже существует

2024-11-29 21:20 UTC, arefev commented on cmd/server/main.go
> +func initStorage(config *Config, cLog *zap.Logger) (storage repository.Storage, storageType string, err error) {
чтобы не определять эти переменные внутри функции, а присваивать им сразу значения и использовать пустой return

2024-11-29 21:59 UTC, s-shpak commented on cmd/server/main.go
> +func initStorage(config *Config, cLog *zap.Logger) (storage repository.Storage, storageType string, err error) {
С моей точки зрения так лучше не делать, потому что:
1. Код сложнее понимать
2. Легче сделать ошибку, случайно, например, затерев интересующую переменную. 

Я, из практики, стараюсь практически никогда не использовать  именованные переменные, потому что они стреляют в ногу. Исключение - когда необходимо вернуть что-то из defer, там по-другому сделать сложно (можно через указатель, но это ещё мне идиоматично).

Но это не ошибка, так что если хочешь их использовать, просто зарезолвь этот комментарий

2024-11-30 13:57 UTC, s-shpak requested changes

2024-11-30 13:57 UTC, s-shpak commented on internal/retry/retry.go
> +		r.wait()
А теперь ты ждешь один раз и теряешь время.

Лучше сделать цикл бесконечным, и проверять условие выхода из цикла после `action`, но перед `wait`

2024-11-30 13:57 UTC, s-shpak commented on internal/retry/retry.go
> +func (r *retry) duration() time.Duration {
```suggestion
func (r *retry) getDuration() time.Duration {
```

2024-12-01 10:09 UTC, arefev commented on cmd/server/main.go
> +func initStorage(config *Config, cLog *zap.Logger) (storage repository.Storage, storageType string, err error) {
пофиксил

2024-12-02 14:58 UTC, s-shpak approved these changes

2024-12-04 21:55 UTC, merged