Iter15
arefev/mtrcstore pull request #4
Opened 2024-12-13 21:40 UTC by arefev

2024-12-16 12:10 UTC, s-shpak requested changes

2024-12-16 12:10 UTC, s-shpak commented on cmd/agent/config.go
>  	Address        = "localhost:8080"
Все эти константы не надо экспортировать

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/repository/memory.go
> +	sync.Mutex
Не стоит встравиать мьютекс в структуру: если она будет экспортирована другим пакетом в будущем, этот пакет получит доступ к методам мьютекса, а мьютексом должна пользоваться только та структура, поля которой он защищает.

Кроме того, правильно хранить указатель на мьютекс, а не сам мьютекс -- мьютекс нельзя копировать после инициализации. Почему это так мы, возмжно, разберем во второй части курса, пока это правило лучше просто запомнить

2024-12-16 12:10 UTC, s-shpak commented on internal/server/middleware/check_sign.go
> +			m.log.Error("check sign failed", zap.Error(err))
Здесь (как и дальше) нужно другое сообщение об ошибке

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
>  func (r *report) MassSend() error {
Этот метод нигде не используется

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
> +	jobs := make(chan model.Metric, numJobs)
Емкость канала с тасками лучше делать равной количеству воркеров. Тасок может быть очень много, число воркеров же всегда будет фиксированным. Емкость канала, равная числу воркеров, увеличивает вероятность, что воркеры будут быстор получать новую задачу и будут меньше простаивать.

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
> +	for a := 1; a <= numJobs; a++ {
Это лучге заменить на `sync.WaitGroup`

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
> +	for w := 1; w <= r.rateLimit; w++ {
Так более идиоматично:

```suggestion
	for w := 0; w < r.rateLimit; w++ {
```

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
> +		go r.worker(w, jobs, results)
Я бы посоветовал не стартовать каждый раз новую горутину, а создать пул воркеров один раз и использовать его

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/service/report.go
> +func NewReport(s Storage, host string, rateLimit int, secretKey string) (report, error) {
Старайся не смешивать назначения разных компонентов: вынеси WorkerPool в отдельную структуру, котоая будет использовать `Report`. Это сделает код менее связанным

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/worker.go
> +			go w.Report.PoolSend()
Это не ограничит количество горутин сверху: если отправка будет занимать боле времени, чем сбор метрик, то количество одновременно исполняемых горутин будет только расти. Эту операцию можно оставить асинхронной, но надо решить проблему с ограничением количества вызовов `PoolSend` (не более одного)

2024-12-16 12:10 UTC, s-shpak commented on internal/agent/worker.go
>  		if period >= w.ReportInterval {
В стандартной библиотеке Go в пакете `time` есть структура `Ticker` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case`

2024-12-17 21:07 UTC, s-shpak requested changes

2024-12-17 21:07 UTC, s-shpak commented on internal/agent/worker.go
> +			if w.WorkerPool.IsEmpty() {
Если ты хочешь убедиться, что ты не заблокируешься здесь, то лучше использовать паттерн `select-default`. Если дело не в этом, то поясни, зачем это

2024-12-17 21:07 UTC, s-shpak commented on internal/agent/worker.go
> +				go w.WorkerPool.Send()
Не надо создавать новые горутины здесь. Тебе достаточно собрать метрики и пачкой записать их в канал. Канал прочтет диспетчер, который раздаст задачи из батча воркером, а после обнулит counter

2024-12-17 21:14 UTC, arefev commented on internal/agent/worker.go
> +			if w.WorkerPool.IsEmpty() {
Здесь хотел проверить, что воркер пул выполнил все предыдущие задания и готов принимать новые. Это на случай, если уже наступило время след. отправки, но у воркера есть еще задания в работе.

2024-12-17 21:50 UTC, arefev commented on internal/agent/worker.go
> +			if w.WorkerPool.IsEmpty() {
В целом понял, что это лишнее, просто уберу

2024-12-23 01:31 UTC, s-shpak approved these changes

2024-12-23 05:38 UTC, merged